// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Data;

#nullable disable

namespace QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006184545_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.BaoCaoSuCo", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaTaiKhoanBaoCao")
                        .HasColumnType("int");

                    b.Property<int>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<string>("MoTaSuCo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MucDoSuCo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("MoiBao");

                    b.HasKey("MaBaoCao");

                    b.HasIndex("MaTaiKhoanBaoCao")
                        .HasDatabaseName("IX_BaoCao_TaiKhoan");

                    b.HasIndex("MaThietBi")
                        .HasDatabaseName("IX_BaoCao_ThietBi");

                    b.HasIndex("MucDoSuCo")
                        .HasDatabaseName("IX_BaoCao_MucDo");

                    b.HasIndex("TrangThai")
                        .HasDatabaseName("IX_BaoCao_TrangThai");

                    b.ToTable("BaoCaoSuCo", t =>
                        {
                            t.HasCheckConstraint("CK_BaoCao_MucDo", "[MucDoSuCo] IN ('Thap', 'TrungBinh', 'Cao', 'KhanCap')");

                            t.HasCheckConstraint("CK_BaoCao_TrangThai", "[TrangThai] IN ('MoiBao', 'DaTiepNhan', 'DangXuLy', 'ChoNghiemThu', 'HoanThanh', 'DaHuy')");
                        });
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.ChiTietXuLy", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaPhieuXuLy")
                        .HasColumnType("int");

                    b.Property<int?>("MaVatTu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungThucHien")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VatTuLinhKien")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaPhieuXuLy")
                        .HasDatabaseName("IX_ChiTiet_Phieu");

                    b.HasIndex("MaVatTu")
                        .HasDatabaseName("IX_ChiTiet_VatTu");

                    b.ToTable("ChiTietXuLy", t =>
                        {
                            t.HasCheckConstraint("CK_ChiTiet_DonGia", "[DonGia] IS NULL OR [DonGia] >= 0");

                            t.HasCheckConstraint("CK_ChiTiet_SoLuong", "[SoLuong] IS NULL OR [SoLuong] > 0");

                            t.HasCheckConstraint("CK_ChiTiet_ThanhTien", "[ThanhTien] IS NULL OR ([SoLuong] IS NOT NULL AND [DonGia] IS NOT NULL AND [ThanhTien] = [SoLuong] * [DonGia])");
                        });
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.KeHoachBaoTri", b =>
                {
                    b.Property<int>("MaKeHoach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKeHoach"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<string>("MucDoUuTien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayDuKien")
                        .HasColumnType("date");

                    b.Property<string>("NoiDungBaoTri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("ChoThucHien");

                    b.HasKey("MaKeHoach");

                    b.HasIndex("MaThietBi")
                        .HasDatabaseName("IX_KeHoach_ThietBi");

                    b.HasIndex("NgayDuKien")
                        .HasDatabaseName("IX_KeHoach_NgayDuKien");

                    b.HasIndex("TrangThai")
                        .HasDatabaseName("IX_KeHoach_TrangThai");

                    b.ToTable("KeHoachBaoTri", t =>
                        {
                            t.HasCheckConstraint("CK_KeHoach_MucDoUuTien", "[MucDoUuTien] IN ('Thap', 'TrungBinh', 'Cao')");

                            t.HasCheckConstraint("CK_KeHoach_TrangThai", "[TrangThai] IN ('ChoThucHien', 'DaPhanCong', 'DangThucHien', 'ChoNghiemThu', 'HoanThanh', 'DaHuy')");
                        });
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.KhuVuc", b =>
                {
                    b.Property<int>("MaKhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuVuc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NguoiPhuTrach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("ViTri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaKhuVuc");

                    b.HasIndex("TenKhuVuc")
                        .IsUnique()
                        .HasDatabaseName("UQ_KhuVuc_Ten");

                    b.ToTable("KhuVuc");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.KyThuatVien", b =>
                {
                    b.Property<int>("MaKyThuatVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKyThuatVien"));

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaKyThuatVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasDatabaseName("UX_KyThuatVien_MaTaiKhoan")
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("KyThuatVien");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.LoaiThietBi", b =>
                {
                    b.Property<int>("MaLoaiThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiThietBi"));

                    b.Property<int>("ChuKyBaoTriMacDinhThang")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoaiThietBi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLoaiThietBi");

                    b.HasIndex("TenLoaiThietBi")
                        .IsUnique()
                        .HasDatabaseName("UQ_LoaiThietBi_Ten");

                    b.ToTable("LoaiThietBi", t =>
                        {
                            t.HasCheckConstraint("CK_LoaiThietBi_ChuKy", "[ChuKyBaoTriMacDinhThang] > 0");
                        });
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.NhatKyDangNhap", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhapNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaTaiKhoan")
                        .HasDatabaseName("IX_NhatKy_MaTaiKhoan");

                    b.HasIndex("ThoiGian")
                        .HasDatabaseName("IX_NhatKy_ThoiGian");

                    b.ToTable("NhatKyDangNhap", t =>
                        {
                            t.HasCheckConstraint("CK_NhatKy_KetQua", "[KetQua] IN ('ThanhCong', 'SaiMatKhau', 'TaiKhoanBiKhoa', 'KhongTonTaiTaiKhoan')");
                        });
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.PhanCongXuLy", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<int>("MaKyThuatVien")
                        .HasColumnType("int");

                    b.Property<int>("MaPhieuXuLy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayKetThucPhanCong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungPhanCong")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("DangHieuLuc");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaKyThuatVien")
                        .HasDatabaseName("IX_PhanCong_KTV");

                    b.HasIndex("MaPhieuXuLy")
                        .IsUnique()
                        .HasDatabaseName("UX_PhanCong_DangHieuLuc")
                        .HasFilter("[TrangThai] = 'DangHieuLuc'");

                    b.HasIndex("TrangThai")
                        .HasDatabaseName("IX_PhanCong_TrangThai");

                    b.HasIndex("MaPhieuXuLy", "TrangThai")
                        .HasDatabaseName("IX_PhanCong_Phieu_TT");

                    b.ToTable("PhanCongXuLy", t =>
                        {
                            t.HasCheckConstraint("CK_PhanCong_TrangThai", "[TrangThai] IN ('DangHieuLuc', 'DaKetThuc')");
                        });
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.PhieuXuLy", b =>
                {
                    b.Property<int>("MaPhieuXuLy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuXuLy"));

                    b.Property<string>("KetQuaXuLy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiXuLy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaBaoCao")
                        .HasColumnType("int");

                    b.Property<int?>("MaKeHoach")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("ChoPhanCong");

                    b.HasKey("MaPhieuXuLy");

                    b.HasIndex("MaBaoCao")
                        .HasDatabaseName("IX_Phieu_BaoCao");

                    b.HasIndex("MaKeHoach")
                        .HasDatabaseName("IX_Phieu_KeHoach");

                    b.HasIndex("TrangThai")
                        .HasDatabaseName("IX_Phieu_TrangThai");

                    b.ToTable("PhieuXuLy", t =>
                        {
                            t.HasCheckConstraint("CK_Phieu_LoaiXuLy", "[LoaiXuLy] IN ('BaoTriDinhKy', 'XuLySuCo')");

                            t.HasCheckConstraint("CK_Phieu_Nguon", "([LoaiXuLy] = 'XuLySuCo' AND [MaBaoCao] IS NOT NULL AND [MaKeHoach] IS NULL) OR ([LoaiXuLy] = 'BaoTriDinhKy' AND [MaKeHoach] IS NOT NULL AND [MaBaoCao] IS NULL)");

                            t.HasCheckConstraint("CK_Phieu_TrangThai", "[TrangThai] IN ('ChoPhanCong', 'DaPhanCong', 'DangXuLy', 'ChoNghiemThu', 'HoanThanh', 'DaHuy')");
                        });
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("KhoaDenNgay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaKhuVuc")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MatKhauSalt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTaoTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("SoLanDangNhapSai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaKhuVuc");

                    b.HasIndex("TenDangNhap")
                        .IsUnique()
                        .HasDatabaseName("UQ_TaiKhoan_TenDangNhap");

                    b.ToTable("TaiKhoan", t =>
                        {
                            t.HasCheckConstraint("CK_TaiKhoan_SoLanSai", "[SoLanDangNhapSai] >= 0");

                            t.HasCheckConstraint("CK_TaiKhoan_VaiTro", "[VaiTro] IN ('Admin', 'KyThuatVien', 'NguoiSuDung')");
                        });
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.TepDinhKem", b =>
                {
                    b.Property<int>("MaTepDinhKem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTepDinhKem"));

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiDoiTuong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDoiTuong")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoanUpload")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayUpload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("TenFileGoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTepDinhKem");

                    b.HasIndex("MaTaiKhoanUpload");

                    b.HasIndex("LoaiDoiTuong", "MaDoiTuong")
                        .HasDatabaseName("IX_TepDinhKem_DoiTuong");

                    b.ToTable("TepDinhKem", t =>
                        {
                            t.HasCheckConstraint("CK_TepDinhKem_Loai", "[LoaiDoiTuong] IN ('ThietBi', 'BaoCaoSuCo', 'ChiTietXuLy')");
                        });
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.ThietBi", b =>
                {
                    b.Property<int>("MaThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThietBi"));

                    b.Property<int>("ChuKyBaoTriThang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhuVuc")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiThietBi")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayBaoTriGanNhat")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayDuaVaoSuDung")
                        .HasColumnType("date");

                    b.Property<string>("SoSerial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaThietBi");

                    b.HasIndex("MaKhuVuc")
                        .HasDatabaseName("IX_ThietBi_KhuVuc");

                    b.HasIndex("MaLoaiThietBi")
                        .HasDatabaseName("IX_ThietBi_Loai");

                    b.HasIndex("SoSerial")
                        .IsUnique()
                        .HasDatabaseName("UQ_ThietBi_SoSerial");

                    b.HasIndex("TinhTrang")
                        .HasDatabaseName("IX_ThietBi_TinhTrang");

                    b.HasIndex("MaLoaiThietBi", "MaKhuVuc", "TinhTrang")
                        .HasDatabaseName("IX_ThietBi_Loc");

                    b.ToTable("ThietBi", t =>
                        {
                            t.HasCheckConstraint("CK_ThietBi_ChuKy", "[ChuKyBaoTriThang] > 0");

                            t.HasCheckConstraint("CK_ThietBi_TinhTrang", "[TinhTrang] IN ('DangHoatDong', 'DangBaoTri', 'TamNgungDoSuCo', 'NgungSuDung')");
                        });
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Kenh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaTaiKhoanNhan")
                        .HasColumnType("int");

                    b.Property<int?>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("ChoGui");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaTaiKhoanNhan")
                        .HasDatabaseName("IX_ThongBao_TaiKhoan");

                    b.HasIndex("MaThietBi");

                    b.HasIndex("TrangThai")
                        .HasDatabaseName("IX_ThongBao_TrangThai");

                    b.ToTable("ThongBao", t =>
                        {
                            t.HasCheckConstraint("CK_ThongBao_Kenh", "[Kenh] IN ('Email', 'HeThong')");

                            t.HasCheckConstraint("CK_ThongBao_TrangThai", "[TrangThai] IN ('ChoGui', 'DaGui', 'Loi')");
                        });
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.VatTu", b =>
                {
                    b.Property<int>("MaVatTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVatTu"));

                    b.Property<decimal>("DonGiaMacDinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaVatTu");

                    b.HasIndex("TenVatTu")
                        .IsUnique()
                        .HasDatabaseName("UQ_VatTu_Ten");

                    b.ToTable("VatTu", t =>
                        {
                            t.HasCheckConstraint("CK_VatTu_DonGia", "[DonGiaMacDinh] >= 0");

                            t.HasCheckConstraint("CK_VatTu_Ton", "[SoLuongTon] >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.BaoCaoSuCo", b =>
                {
                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.TaiKhoan", "TaiKhoanBaoCao")
                        .WithMany("BaoCaoSuCos")
                        .HasForeignKey("MaTaiKhoanBaoCao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.ThietBi", "ThietBi")
                        .WithMany("BaoCaoSuCos")
                        .HasForeignKey("MaThietBi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoanBaoCao");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.ChiTietXuLy", b =>
                {
                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.PhieuXuLy", "PhieuXuLy")
                        .WithMany("ChiTietXuLys")
                        .HasForeignKey("MaPhieuXuLy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.VatTu", "VatTu")
                        .WithMany("ChiTietXuLys")
                        .HasForeignKey("MaVatTu")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PhieuXuLy");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.KeHoachBaoTri", b =>
                {
                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.ThietBi", "ThietBi")
                        .WithMany("KeHoachBaoTris")
                        .HasForeignKey("MaThietBi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.KyThuatVien", b =>
                {
                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KyThuatVien")
                        .HasForeignKey("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.KyThuatVien", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.NhatKyDangNhap", b =>
                {
                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("NhatKyDangNhaps")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.PhanCongXuLy", b =>
                {
                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.KyThuatVien", "KyThuatVien")
                        .WithMany("PhanCongXuLys")
                        .HasForeignKey("MaKyThuatVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.PhieuXuLy", "PhieuXuLy")
                        .WithMany("PhanCongXuLys")
                        .HasForeignKey("MaPhieuXuLy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KyThuatVien");

                    b.Navigation("PhieuXuLy");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.PhieuXuLy", b =>
                {
                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.BaoCaoSuCo", "BaoCaoSuCo")
                        .WithMany("PhieuXuLys")
                        .HasForeignKey("MaBaoCao")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.KeHoachBaoTri", "KeHoachBaoTri")
                        .WithMany("PhieuXuLys")
                        .HasForeignKey("MaKeHoach")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaoCaoSuCo");

                    b.Navigation("KeHoachBaoTri");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.KhuVuc", "KhuVuc")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaKhuVuc")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhuVuc");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.TepDinhKem", b =>
                {
                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.TaiKhoan", "TaiKhoanUpload")
                        .WithMany("TepDinhKems")
                        .HasForeignKey("MaTaiKhoanUpload")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoanUpload");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.ThietBi", b =>
                {
                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.KhuVuc", "KhuVuc")
                        .WithMany("ThietBis")
                        .HasForeignKey("MaKhuVuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.LoaiThietBi", "LoaiThietBi")
                        .WithMany("ThietBis")
                        .HasForeignKey("MaLoaiThietBi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhuVuc");

                    b.Navigation("LoaiThietBi");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.ThongBao", b =>
                {
                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.TaiKhoan", "TaiKhoanNhan")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaTaiKhoanNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.ThietBi", "ThietBi")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaThietBi")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoanNhan");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.BaoCaoSuCo", b =>
                {
                    b.Navigation("PhieuXuLys");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.KeHoachBaoTri", b =>
                {
                    b.Navigation("PhieuXuLys");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.KhuVuc", b =>
                {
                    b.Navigation("TaiKhoans");

                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.KyThuatVien", b =>
                {
                    b.Navigation("PhanCongXuLys");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.LoaiThietBi", b =>
                {
                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.PhieuXuLy", b =>
                {
                    b.Navigation("ChiTietXuLys");

                    b.Navigation("PhanCongXuLys");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.TaiKhoan", b =>
                {
                    b.Navigation("BaoCaoSuCos");

                    b.Navigation("KyThuatVien");

                    b.Navigation("NhatKyDangNhaps");

                    b.Navigation("TepDinhKems");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.ThietBi", b =>
                {
                    b.Navigation("BaoCaoSuCos");

                    b.Navigation("KeHoachBaoTris");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("QuanLyBaoTriThietBi_UNETI01_TI17A4HN.Models.VatTu", b =>
                {
                    b.Navigation("ChiTietXuLys");
                });
#pragma warning restore 612, 618
        }
    }
}
